config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resources :empty_rooms do
    collection do
      get :index_search
    end
  end



  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empty_room.rb
class EmptyRoom < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empty_rooms_controller.rb
class EmptyRoomsController < ApplicationController
  before_action :set_empty_room, only: [:show, :edit, :update, :destroy]

  # GET /empty_rooms
  # GET /empty_rooms.json
  def index
    @empty_rooms = EmptyRoom.all
  end
  def index_search
    if params[:conditions][:name].present?
      @empty_rooms = EmptyRoom.where('name LIKE ?', "%#{params[:conditions][:name]}%")
    else
      @empty_rooms = EmptyRoom.all
    end

    respond_to do |format|
        format.js { render :index_table }
    end
  end

  # GET /empty_rooms/1
  # GET /empty_rooms/1.json
  def show
  end

  # GET /empty_rooms/new
  def new
    @empty_room = EmptyRoom.new
  end

  # GET /empty_rooms/1/edit
  def edit
  end

  # POST /empty_rooms
  # POST /empty_rooms.json
  def create
    @empty_room = EmptyRoom.new(empty_room_params)

    respond_to do |format|
      if @empty_room.save
        format.html { redirect_to @empty_room, notice: 'Empty room was successfully created.' }
        format.json { render :show, status: :created, location: @empty_room }
      else
        format.html { render :new }
        format.json { render json: @empty_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empty_rooms/1
  # PATCH/PUT /empty_rooms/1.json
  def update
    respond_to do |format|
      if @empty_room.update(empty_room_params)
        format.html { redirect_to @empty_room, notice: 'Empty room was successfully updated.' }
        format.json { render :show, status: :ok, location: @empty_room }
      else
        format.html { render :edit }
        format.json { render json: @empty_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empty_rooms/1
  # DELETE /empty_rooms/1.json
  def destroy
    @empty_room.destroy
    respond_to do |format|
      format.html { redirect_to empty_rooms_url, notice: 'Empty room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empty_room
      @empty_room = EmptyRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empty_room_params
      params.require(:empty_room).permit(:status, :arrangement, :name, :number, :leave_status, :day_to_leave, :benefit, :day_to_enter, :area, :rent, :common_fee, :thanks_money_status, :thanks_money, :thanks_money_month, :deposit_status, :deposit, :deposit_month, :station, :parking_status, :parking, :pet, :gas, :memo, :key ,:url_info)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empty_room_helper.rb
module EmptyRoomHelper

  def get_status_name(status_info)

    case status_info
    when 0
      return "未定"
    when 1
      return "1番手あり"
    when 2
      return "審査中"
    when 3
      return "その他"
    else
      return "想定外データ"
    end

  end

  def get_arrangement_name(arrangement_info)

    case arrangement_info
    when 0
      return "1R"
    when 1
      return "1K"
    when 2
      return "1DK"
    when 3
      return "1LDK"
    when 4
      return "2K"
    when 5
      return "2DK"
    when 6
      return "2LDK"
    when 7
      return "3K"
    when 8
      return "3DK"
    when 9
      return "3LDK"
    when 10
      return "4K"
    when 11
      return "4DK"
    when 12
      return "4LDK"
    when 13
      return "5K以上"
    else
      return "想定外データ"
    end

  end

  def get_parking_status_name(status_info)

    case status_info
    when 0
      return "あり（有料）"
    when 1
      return "空きなし"
    when 2
      return "あり（無料）"
    when 3
      return "無し"
    else
      return "想定外データ"
    end

  end

  def get_pet_info(info)
    if info == 0
      return "可"
    else
      return "不可"
    end
  end

    def get_gas_name(gas_info)

      case gas_info
      when 0
        return "東京ガス"
      when 1
        return "プロパン"
      when 2
        return "オール電化"
      else
        return "想定外データ"
      end

    end

end

app/views/empty_rooms/_form.html.erb
<%= form_with(model: empty_room, local: true) do |form| %>
  <% if empty_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(empty_room.errors.count, "error") %> prohibited this empty_room from being saved:</h2>

      <ul>
      <% empty_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="line_info">
    <%= form.label "進捗" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :status, 0 %><%= "未定" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :status, 1 %><%= "1番手あり" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :status, 2 %><%= "審査中" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :status, 3 %><%= "その他" %>
      </label>
    </span>
    <%# <%= form.number_field :status ,class: "line_content_2"%> %>
  </div>

  <div class="line_info">
    <%= form.label "間取" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 0 %><%= "1R" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 1 %><%= "1K" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 2 %><%= "1DK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 3 %><%= "1LDK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 4 %><%= "2K" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 5 %><%= "2DK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 6 %><%= "2LDK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 7 %><%= "3K" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 8 %><%= "3DK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 9 %><%= "3LDK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 10 %><%= "4K" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 11 %><%= "4DK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 12 %><%= "4LDK" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :arrangement, 13 %><%= "5K以上" %>
      </label>
    </span>
    <%# <%= form.number_field :arrangement ,class: "line_content_2"%> %>
  </div>

  <div class="line_info">
    <%= form.label "アパート名" ,class: "line_content_1"%>
    <%= form.text_field :name ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "室番" ,class: "line_content_1"%>
    <%= form.text_field :number ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "空き状態" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :leave_status, 0 %><%= "現空" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :leave_status, 9 %><%= "入居中" %>
      </label>
    </span>
    <%# <%= form.number_field :leave_status ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "退室予定日" ,class: "line_content_1"%>
    <%= form.date_field :day_to_leave ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "Fレント、特典等" ,class: "line_content_1"%>
    <%= form.text_field :benefit ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "入居可時期" ,class: "line_content_1"%>
    <%= form.text_field :day_to_enter ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "面積（㎡）" ,class: "line_content_1"%>
    <%= form.text_field :area ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "賃料" ,class: "line_content_1"%>
    <%= form.number_field :rent ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "共益費" ,class: "line_content_1"%>
    <%= form.number_field :common_fee ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "礼金" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :thanks_money_status, 0 %><%= "金額" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :thanks_money_status, 1 %><%= "月数" %>
      </label>
    </span>
    <%# <%= form.number_field :thanks_money_status ,class: "line_content_2"%> %>
  </div>

  <div class="line_info">
    <%= form.label "礼金（金額）" ,class: "line_content_1"%>
    <%= form.number_field :thanks_money ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "礼金（月数）" ,class: "line_content_1"%>
    <%= form.text_field :thanks_money_month ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "敷金" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :deposit_status, 0 %><%= "金額" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :deposit_status, 1 %><%= "月数" %>
      </label>
    </span>
    <%# <%= form.number_field :deposit_status ,class: "line_content_2"%> %>
  </div>

  <div class="line_info">
    <%= form.label "敷金（金額）" ,class: "line_content_1"%>
    <%= form.number_field :deposit ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "敷金（月数）" ,class: "line_content_1"%>
    <%= form.text_field :deposit_month ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "最寄り駅" ,class: "line_content_1"%>
    <%= form.text_field :station ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "駐車場" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :parking_status, 0 %><%= "あり（有料）" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :parking_status, 1 %><%= "空きなし" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :parking_status, 2 %><%= "あり（無料）" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :parking_status, 3 %><%= "無し" %>
      </label>
    </span>
    <%# <%= form.number_field :parking_status ,class: "line_content_2"%> %>
  </div>

  <div class="line_info">
    <%= form.label "駐車場料金" ,class: "line_content_1"%>
    <%= form.number_field :parking ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "ペット" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :pet, 0 %><%= "可" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :pet, 9 %><%= "不可" %>
      </label>
    </span>
    <%# <%= form.number_field :pet ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "ガス" ,class: "line_content_1"%>
    <span class = "input_radio_btn_line">
      <label class = "input_radio_btn">
        <%= form.radio_button :gas, 0 %><%= "東京ガス" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :gas, 1 %><%= "プロパン" %>
      </label>
      <label class = "input_radio_btn">
        <%= form.radio_button :gas, 2 %><%= "オール電化" %>
      </label>
    </span>
    <%# <%= form.number_field :gas ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "備考" ,class: "line_content_1"%>
    <%= form.text_field :memo ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "鍵" ,class: "line_content_1"%>
    <%= form.text_field :key ,class: "line_content_2"%>
  </div>

  <div class="line_info">
    <%= form.label "スーモURL" ,class: "line_content_1"%>
    <%= form.text_field :url_info ,class: "line_content_2"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/empty_rooms/_index_table.html.erb
  <table >
    <thead>
      <tr>
        <th class = "small_cell">進捗</th>
        <th class = "small_cell">間取</th>
        <th class = "middle_cell">アパート名</th>
        <th class = "small_cell">室番</th>
        <th class = "small_cell">空き状態</th>
        <!-- <th>退室予定日</th> -->
        <th class = "middle_cell">Fレント、特典等</th>
        <th class = "middle_cell">入居可時期</th>
        <th class = "middle_cell">面積（㎡）</th>
        <th class = "small_cell">賃料</th>
        <th class = "small_cell">共益費</th>
        <th class = "small_cell">礼金</th>
        <!-- <th>礼金（金額）</th>
        <th>礼金（月数）</th> -->
        <th class = "small_cell">敷金</th>
        <!-- <th>敷金（金額）</th>
        <th>敷金（月数）</th> -->
        <th class = "wide_cell">最寄り駅</th>
        <th class = "middle_cell">駐車場</th>
        <th class = "small_cell">(料金)</th>
        <th class = "small_cell">ペット</th>
        <th class = "small_cell">ガス</th>
        <th class = "wide_cell">備考</th>
        <th class = "wide_cell">鍵</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% empty_rooms.each do |empty_room| %>
        <tr>
          <td><%= get_status_name(empty_room.status) %></td>
          <td><%= get_arrangement_name(empty_room.arrangement) %></td>
          <td><%= empty_room.name %></td>
          <td><%= empty_room.number %></td>


          <td>
            <% if empty_room.leave_status == 0 %>
              <%= "現空" %>
            <% else %>
              <%= empty_room.day_to_leave %>退去予定
            <% end %>
          </td>

          <!-- <td><%= empty_room.leave_status %></td>
          <td><%= empty_room.day_to_leave %></td> -->

          <td><%= empty_room.benefit %></td>
          <td><%= empty_room.day_to_enter %></td>
          <td><%= empty_room.area %></td>
          <td><%= empty_room.rent %></td>
          <td><%= empty_room.common_fee %></td>

          <td>
            <% if empty_room.thanks_money_status == 0 %>
              <%= empty_room.thanks_money %>円
            <% else %>
              <%= empty_room.thanks_money_month %>ヶ月
            <% end %>
          </td>
          <!-- <td><%= empty_room.thanks_money_status %></td>
          <td><%= empty_room.thanks_money %></td>
          <td><%= empty_room.thanks_money_month %></td> -->

          <td>
            <% if empty_room.deposit_status == 0 %>
              <%= empty_room.deposit %>円
            <% else %>
              <%= empty_room.deposit_month %>ヶ月
            <% end %>
          </td>
          <!-- <td><%= empty_room.deposit_status %></td>
          <td><%= empty_room.deposit %></td>
          <td><%= empty_room.deposit_month %></td> -->

          <td><%= empty_room.station %></td>

          <td><%= get_parking_status_name(empty_room.parking_status) %></td>
          <td><%= empty_room.parking %>円</td>
          <td><%= get_pet_info(empty_room.pet) %></td>
          <td><%= get_gas_name(empty_room.gas) %></td>
          <td><%= empty_room.memo %></td>
          <td><%= empty_room.key %></td>
          <!-- <td><%= link_to 'Show', empty_room %></td> -->
          <td>
            <% if empty_room.url_info.present? %>
              <%= link_to "sumo", empty_room.url_info, class: "btn btn-primary "  %>
            <% end %>
          </td>

          <td><%= link_to 'Edit', edit_empty_room_path(empty_room) %></td>
          <td><%= link_to 'Destroy', empty_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>


        </tr>
      <% end %>
    </tbody>
  </table>

app/views/empty_rooms/edit.html.erb
<h1>空室物件更新</h1>

<%= render 'form', empty_room: @empty_room %>

<%= link_to 'Show', @empty_room %> |
<%= link_to 'Back', empty_rooms_path %>

app/views/empty_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h4>空室物件一覧</h4>

<div class="search_box">

  <h5 class= "search_box_title"><%= t('item.search_title') %></h5>

  <%= form_with scope: :conditions, url:index_search_empty_rooms_path,method: :get ,remote: true do |form| %>

    <div class="search_box_cell search_cell_1_2">
      <%= form.label "物件名" ,class: "search_label" %>
      <%= form.text_field :name %>
      <%# <%= form.label ":" + current_user.name,id: :indicate_user_name  %>
    </div>


    <div class="search_box_line">
      <%= form.submit "検索" , id: "btn btn-primary "  %>
    </div>
  <% end %>
</div>


<div class = "index_table" id = "index_table" >
  
  <%= render 'index_table', empty_rooms: @empty_rooms %>

</div>
<br>

<%= link_to 'New Empty Room', new_empty_room_path %>

app/views/empty_rooms/index_table.js.erb
$("#index_table").html("<%= j(render 'empty_rooms/index_table', { empty_rooms: @empty_rooms }) %>")

app/views/empty_rooms/new.html.erb
<h1>空室物件データ作成</h1>

<%= render 'form', empty_room: @empty_room %>

<%= link_to 'Back', empty_rooms_path %>

app/views/empty_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @empty_room.status %>
</p>

<p>
  <strong>Arrangement:</strong>
  <%= @empty_room.arrangement %>
</p>

<p>
  <strong>Name:</strong>
  <%= @empty_room.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @empty_room.number %>
</p>

<p>
  <strong>Leave status:</strong>
  <%= @empty_room.leave_status %>
</p>

<p>
  <strong>Day to leave:</strong>
  <%= @empty_room.day_to_leave %>
</p>

<p>
  <strong>Benefit:</strong>
  <%= @empty_room.benefit %>
</p>

<p>
  <strong>Day to enter:</strong>
  <%= @empty_room.day_to_enter %>
</p>

<p>
  <strong>Area:</strong>
  <%= @empty_room.area %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @empty_room.rent %>
</p>

<p>
  <strong>Common fee:</strong>
  <%= @empty_room.common_fee %>
</p>

<p>
  <strong>Thanks money status:</strong>
  <%= @empty_room.thanks_money_status %>
</p>

<p>
  <strong>Thanks money:</strong>
  <%= @empty_room.thanks_money %>
</p>

<p>
  <strong>Thanks money month:</strong>
  <%= @empty_room.thanks_money_month %>
</p>

<p>
  <strong>Deposit status:</strong>
  <%= @empty_room.deposit_status %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @empty_room.deposit %>
</p>

<p>
  <strong>Deposit month:</strong>
  <%= @empty_room.deposit_month %>
</p>

<p>
  <strong>Station:</strong>
  <%= @empty_room.station %>
</p>

<p>
  <strong>Parking status:</strong>
  <%= @empty_room.parking_status %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @empty_room.parking %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @empty_room.pet %>
</p>

<p>
  <strong>Gas:</strong>
  <%= @empty_room.gas %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @empty_room.memo %>
</p>

<p>
  <strong>Key:</strong>
  <%= @empty_room.key %>
</p>

<%= link_to 'Edit', edit_empty_room_path(@empty_room) %> |
<%= link_to 'Back', empty_rooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yatiyo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
dddddd

<%= link_to "空欄確認", empty_rooms_path, class: "btn btn-primary "  %>